# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShinyWaddleCli < Formula
  desc ""
  homepage ""
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.0.8/shiny-waddle-cli_1.0.8_darwin_x86_64.tar.gz"
      sha256 "86d2717b60b60f935de4a525da021949dea670327c680ed80bd3f5f8bdbcf451"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.0.8/shiny-waddle-cli_1.0.8_darwin_arm64.tar.gz"
      sha256 "4cab585dfde49e54571ea1b43a6ed6dde3603af558c8be612a64aba08824ae14"

      def install
        bin.install "cg-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.0.8/shiny-waddle-cli_1.0.8_linux_x86_64.tar.gz"
      sha256 "06342fdf9935bf7a77f8a3850ebf175df63ab8e3d922637f2988aa6979e9b169"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.0.8/shiny-waddle-cli_1.0.8_linux_armv7.tar.gz"
      sha256 "7bef60169443f907cf7bd469b2cb5188ddd5973a5652c9e5054128b338fafcf8"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.0.8/shiny-waddle-cli_1.0.8_linux_arm64.tar.gz"
      sha256 "0e9ebf07b6f7fafffaab5ed48f0fb61d347b268ed7cc902327e27deac0afdf94"

      def install
        bin.install "cg-cli"
      end
    end
  end
end
