# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShinyWaddleCli < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/Valkyrie00/shiny-waddle"
  version "1.1.0-alpha.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.1.0-alpha.1/shiny-waddle-cli_1.1.0-alpha.1_darwin_x86_64.tar.gz"
      sha256 "c853c04b53a752b95f8ff9e9edd0bd3f78244331fcd2237e01ea2a2a2d22c974"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.1.0-alpha.1/shiny-waddle-cli_1.1.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "6a2eee543febcdaeb69f077d19041207ba0a26e8a90d66636d7ac7c8fcc04eb9"

      def install
        bin.install "cg-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.1.0-alpha.1/shiny-waddle-cli_1.1.0-alpha.1_linux_armv6.tar.gz"
      sha256 "2c1374642e25c577ab327b468257222280b954336884a1649bf1e86a8470cee0"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.1.0-alpha.1/shiny-waddle-cli_1.1.0-alpha.1_linux_x86_64.tar.gz"
      sha256 "4b4e00d1bc4676c892f1506896823b1e3b9c723839a4396fca79b3305e081594"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Valkyrie00/shiny-waddle/releases/download/v1.1.0-alpha.1/shiny-waddle-cli_1.1.0-alpha.1_linux_arm64.tar.gz"
      sha256 "f6b4a78b4b45249676dca69a4d5acb8814100ccd7d069efacc07cdc0166e6a43"

      def install
        bin.install "cg-cli"
      end
    end
  end
end
